### ISSUE TITLE
Checkbox Treeview Image Replacing Checkbox

### ISSUE THREAD

**Issue by heesuju** [TkinterEP/ttkwidgets#103]
I am listing several folders using checkbox preview.
If a folder has an image file inside, the image is inserted into the row. 
However, rows that have an image does not have a checkbox as if the image is replacing the checkbox.

Is this the intended behavior? 
Is there a way to add the image to another column?
Thank you in advance.

**Comment by rdbende** [comment]
Hello,

Yes this is the intended behavior, since a treeview row can only contain one image.
However, this isn't optimal and I think there may be a way to hack around this. Unfortunately there hasn't been much activity on the project in the last 3 years, so I don't think it would be fixed soon.

**Comment by heesuju** [comment]
Guess I'll just stick with checkboxes instead.
Thank you for the answer!
