### ISSUE TITLE
xscroll for ttkwidgets.Checkboxtreeview

### ISSUE THREAD

**Issue by anantha1987** [TkinterEP/ttkwidgets#49]
Hi, 
I am looking for xscroll to see the large text in Checkboxtreeview. can you please help me.

Thanks,
Anantha

**Comment by RedFantom** [comment]
Unfortunately, the horizontal scrolling capabilities of the `Treeview` widget are limited. The `CheckboxTreeview` does not have different behaviour in this regard: Apart from the checkbox functionality it is the same widget. Therefore, there are no specific options available.

There are questions and answers about this topic on StackOverflow, such as [this one](https://stackoverflow.com/questions/14359906/horizontal-scrolling-wont-activate-for-ttk-treeview-widget), [this one](https://stackoverflow.com/questions/13205727/using-ttk-treeview-how-can-i-get-horizontal-scrolling-to-work-as-expected) and [this one](https://stackoverflow.com/questions/42996627/horizontal-scrollbar-treeview-in-tkinter?noredirect=1). There are certainly more, these are just a few examples I found in less than a minute.

Read the answers and documentation carefully and determine whether a `Treeview` in general can accomplish what you want. The `CheckboxTreeview` will be the same in regards to the horizontal scrolling.
