### ISSUE TITLE
Does ttkwidgets.Checkboxtreeview support insert image on each check item?

### ISSUE THREAD

**Issue by wekay102200** [TkinterEP/ttkwidgets#54]
like below:
![2019-12-10_235747](https://user-images.githubusercontent.com/18589915/70578127-d39e8c80-1be7-11ea-9bae-a71c1702c40a.png)

**Comment by RedFantom** [comment]
`CheckboxTreeview` does not allow inserting additional images, as the images are already in use for the checkboxes. You may be able to build a new implementation where you combine the checkbox images with your icons, but a `ttk.Treeview` can never display more than one image per row. If you want that, then there are other implementations out there, but generally they are not themed, you have to compile them yourself from C code and it will be a lot of searching without any additional support. Unfortunately, the limitation of a single image cannot be circumvented.
