### ISSUE TITLE
ChecklistTreeView Images do not Appear - macos 10.15.2

### ISSUE THREAD

**Issue by gregorosaurus** [TkinterEP/ttkwidgets#56]
I'm running the example for ChecklistTreeView on macos 10.15.2, and the images for the checklist do not appear. 

**Python version:** Python 3.7.6 - installed from homebrew 
**OS:** macos 10.15.2
**ttkwidgets version:** 0.10.0

Example being run:

```
from ttkwidgets import *
import tkinter as tk
root = tk.Tk()
tree = CheckboxTreeview(root)
tree.pack()

tree.insert("", "end", "1", text="1")
tree.insert("1", "end", "11", text="11")
tree.insert("1", "end", "12",  text="12")
tree.insert("11", "end", "111", text="111")
tree.insert("", "end", "2", text="2")

root.mainloop()

```
**result:**
![Screenshot 2020-01-23 23 20 09](https://user-images.githubusercontent.com/38509083/73048591-eaffa500-3e36-11ea-8845-e79cbc6a6756.png)

If I update the images to be converted to RGB in **checkboxtreeview.py**, the pictures are displayed:
```
self.im_checked = ImageTk.PhotoImage(Image.open(IM_CHECKED).convert('RGB'), master=self)
self.im_unchecked = ImageTk.PhotoImage(Image.open(IM_UNCHECKED).convert('RGB'), master=self)
self.im_tristate = ImageTk.PhotoImage(Image.open(IM_TRISTATE).convert('RGB'), master=self)
```
![Screenshot 2020-01-23 23 30 08](https://user-images.githubusercontent.com/38509083/73049059-804f6900-3e38-11ea-8ba5-b16d4bbe56bf.png)

Similar issue: [https://stackoverflow.com/questions/29708822/png-image-not-showing-up-when-using-tkinter-pillow-pil-in-python-2-7-under-m](https://stackoverflow.com/questions/29708822/png-image-not-showing-up-when-using-tkinter-pillow-pil-in-python-2-7-under-m)

**Comment by j4321** [comment]
@gregorosaurus  I think you may have the same problem as in https://github.com/TkinterEP/ttkwidgets/pull/31. This issue was solved after the release of version 0.10.0 so can you try with a newer version of the module? 

@RedFantom Could you put v0.11.0 on pypi? Or I can do it if you add me as a maintainer on pypi (my username is j_4321).

**Comment by RedFantom** [comment]
@j4321 You are now a maintainer on PyPI. I have just uploaded v0.11.0, so it is available now, but for future releases it would indeed be a good idea to have someone else able to upload in case I forget again.

**Comment by gregorosaurus** [comment]
@j4321  Thanks for that! I totally missed issue #31 . My bad.
