### ISSUE TITLE
CheckboxTreeview doesn't work when the treeview is populated via SQLite query

### ISSUE THREAD

**Issue by OogieM** [TkinterEP/ttkwidgets#62]
I'm trying to use the CheckboxTreeview from ttkwidgets to put checkboxes in front of each line of a treeview I populate with an SQLite query where each row returned by the cursor should be a row in the treeview. I either get a blank tree with checkboxes or the same view as I get with a standard treeview. Is this something that can be supported or am I just doing it completely wrong?

**Comment by RedFantom** [comment]
Thank you for opening an issue! Without knowing what you are doing, I'm afraid I can't say whether you're doing something wrong or not. Could you perhaps share a small example that I can run to see the problem you're running into?

**Comment by OogieM** [comment]
I can show you the code that I'm using and the output but I can't really send you the entire database.
`from ttkwidgets import CheckboxTreeview
import tkinter as tk
import sqlite3
root = tk.Tk()
tree = CheckboxTreeview(root)
connection = sqlite3.connect('lambtracker_db.sqlite')
cursor = connection.cursor()
cmd = "select id_deathreasonid, death_reason from death_reason_table"
cursor.execute(cmd)
rows = cursor.fetchall()
for row in rows:
    print(row)
    tree.insert('', 'end', values=row)
tree.pack()
root.mainloop()`
produces this result
![Screen Shot 2020-06-30 at 1 41 19 PM](https://user-images.githubusercontent.com/2394446/86244390-23817880-bb65-11ea-848c-797738016241.png)
I can verify that the command is working properly because I do get this printed out in the console
`(1, 'Died Unknown')
(2, 'Died Old Age')
(3, 'Died Predator')
(4, 'Died Illness')
(5, 'Died Injury')
(6, 'Died Stillborn')
(7, 'Died Birth Defect')
(8, 'Died Meat')
(9, 'Died Euthanized')
(10, 'Died Dystocia')
(11, 'Died Other')
(12, 'Died Culled')`
standard tree view like this works properly
`import tkinter as tk
from tkinter import ttk
import sqlite3
root = tk.Tk()
tree = ttk.Treeview(root, column=("column1", "column2"), show='headings')
tree.heading("#1", text="id_deathreasonid")
tree.heading("#2", text="Death Reason")
connection = sqlite3.connect('lambtracker_db.sqlite')
cursor = connection.cursor()
cmd = "select id_deathreasonid, death_reason from death_reason_table"
cursor.execute(cmd)
rows = cursor.fetchall()
for row in rows:
    print(row)
    tree.insert('', 'end', values=row)
tree.pack()
root.mainloop()`
![Screen Shot 2020-06-30 at 1 41 37 PM](https://user-images.githubusercontent.com/2394446/86244555-617e9c80-bb65-11ea-8fc2-99fcbe8ceef1.png)
If I add the same column and header info to the CheckboxTreeview version it looks the same as the standard ttk.Treeview version

`from ttkwidgets import CheckboxTreeview
import tkinter as tk
import sqlite3
root = tk.Tk()
tree = CheckboxTreeview(root, column=("column1", "column2"), show='headings')
tree.heading("#1", text="id_deathreasonid")
tree.heading("#2", text="Death Reason")
connection = sqlite3.connect('lambtracker_db.sqlite')
cursor = connection.cursor()
cmd = "select id_deathreasonid, death_reason from death_reason_table"
cursor.execute(cmd)
rows = cursor.fetchall()
for row in rows:
    print(row)
    tree.insert('', 'end', values=row)
tree.pack()
root.mainloop()`

I'm trying to get checkboxes in front of the rows in a treeview when I fill the tree view via an SQLite query. I will use those later as a selection for subsets of the query to do something else with.

**Comment by OogieM** [comment]
I'll see if I can send you a simple database with just that demo table in it. I'm actually using it on another table but those data are private and I can't share.

**Comment by RedFantom** [comment]
While this is not a verifiable example, I'm pretty sure what is going wrong. You are passing `show="headings"` to the `__init__` of `CheckboxTreeview`. If you override the default behaviour (which `CheckboxTreeview` inherits from the plain `Treeview`), it will remove the `tree` from being shown. Normally, both are shown.

So, just changing 
```python
tree = CheckboxTreeview(root, column=("column1", "column2"), show='headings')
```
to
```python
tree = CheckboxTreeview(root, column=("column1", "column2"), show=("headings", "tree"))
```
will fix your problem.

You see, the images are shown in column `#0`, which is always created by the `Treeview`. It is the only column that can display images without resorting to other, more complicated widgets. If you do not include `tree` in the `show` keyword argument, this column is not shown, hence it looks like a normal `Treeview`. After all, the checkboxes are the only visible change of the `CheckboxTreeview` compared to the normal `Treeview`. The example below shows the difference more clearly.

```python
from ttkwidgets import CheckboxTreeview
import tkinter as tk
from random import choice


window = tk.Tk()

data = [
    (i, choice(["Hello", "World", "Universe", "Multiverse"]))
    for i in range(10)
]

tree_without = CheckboxTreeview(window, columns=("number", "word"), show=("headings",))
tree_with = CheckboxTreeview(window, columns=("number", "word"), show=("headings", "tree"))

for tree in (tree_without, tree_with):
    tree.heading("#1", text="Number")
    tree.heading("#2", text="Word")

    for item in data:
        print(data)
        tree.insert("", tk.END, values=item)

tree_without.pack(side=tk.LEFT)
tree_with.pack(side=tk.RIGHT)

window.mainloop()
```

The result:
![Screenshot from 2020-07-01 18-48-13](https://user-images.githubusercontent.com/15170036/86270437-86a5f600-bbcb-11ea-8bb5-28fd8205fa85.png)

I am not certain whether this is documented behaviour, but I think it ought to be, so I will check and make sure. I hope this helps you out. If so, you can close the issue. If not, then feel free to ask!

**Comment by OogieM** [comment]
Wonderful! That does fix the problem. I'm a beginner in Python, coming from an Android Java world and trying to spin up fast and getting lost a bit. Thank you so much and yes I'll close the issue. I'm sure I'll have other questions on use of the CheckboxTreeview eventually but I'm not even far enough to formulate a coherent question.
