### ISSUE TITLE
Make widgets like checkboxtreeview scrollable?

### ISSUE THREAD

**Issue by andowinger** [TkinterEP/ttkwidgets#68]
I have a list with about 200 entries and probably I am missing something here :)

What is the suggested way to use the (very nice) checkboxtreeview widget with a vertical scrollbar?
Do I have to cover that showhow with a scrollable canvas?
Or could such a vertical scrollbar be added as a native part of the widget? If yes: How would be the approach for the latter?

**Comment by RedFantom** [comment]
`CheckboxTreeview` behaves the same with `Scrollbar`s as `Treeview` does. So configuring a `CheckboxTreeview` with a vertical `Scrollbar` can be done like:
```python
from ttkwidgets import CheckboxTreeview
import tkinter as tk
from tkinter import ttk
from random import choice


window = tk.Tk()

data = [
    (i, choice(["Hello", "World", "Universe", "Multiverse"]))
    for i in range(200)
]

scroll = ttk.Scrollbar(window, orient=tk.VERTICAL)
# yscrollcommand indicates that the Treeview has to tell Scrollbar about how much vertical overflow there is
tree = CheckboxTreeview(window, yscrollcommand=scroll.set, height=4, columns=("index", "word")) 
scroll.config(command=tree.yview)  # Make the Scrollbar actually set the 'yview'

for item in data:
    tree.insert("", tk.END, values=item)

tree.grid(column=0, row=0, sticky="nswe")
scroll.grid(column=1, row=0, sticky="ns")

window.mainloop()
```

Please let me know if this answers your question!

**Comment by andowinger** [comment]
Thanks a lot, this answers it!
