### ISSUE TITLE
Hooks and validated entries missing from Pypi package

### ISSUE THREAD

**Issue by rdbende** [TkinterEP/ttkwidgets#81]
I have a [project](https://github.com/rdbende/tkinterDnD) that needs `ttkwidgets.hook` module, but unfortunately it's not included in the Pypi package. The validated_entries submodule also missing from the `setup.py` file. These should be updated.

**Comment by krewshul** [comment]
to further add to @rdbende issue they opened I am getting the same error. 

- using python 3.9
- MacBook Pro

including the output below:

`  File "<redacted> /ttkwidgets/examples/example_hook.py", line 7, in <module>`
   ` from ttkwidgets.hook import hook_ttk_widgets`
`  File "<redacted> /lib/python3.9/site-packages/ttkwidgets-0.11.0-py3.9.egg/ttkwidgets/__init__.py", line 15, in <module>`
 `   from ttkwidgets.validated_entries.numbers import (`
` ModuleNotFoundError: No module named 'ttkwidgets.validated_entries'`

**Comment by RedFantom** [comment]
@krewshul Thank you for your PR, I merged It :+1:

I will be pushing an updated PyPI package soon.

**Comment by RedFantom** [comment]
We are now at 0.12.0, and [it's on PyPI](https://pypi.org/project/ttkwidgets/#history).
