### ISSUE TITLE
Library ttkwidgets==0.12.0 automatically installed under Python 2

### ISSUE THREAD

**Issue by namruf15** [TkinterEP/ttkwidgets#84]
**WHAT:**
Library ttkwidgets==0.12.0 automatically installed under Python 2 which fails the execution

**WHY:**
Lack of python_requires record within setup.py

**SOLUTION**
Add _python_requires='>=3.6'_ into setup.py and blacklist the 0.12.0 version

**LOGS:**
   
    ERROR: Command errored out with exit status 1:
     command: /home/ute/Repositories/venvs/test_test/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2S13Og/ttkwidgets/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2S13Og/ttkwidgets/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-JOS1DZ
         cwd: /tmp/pip-install-2S13Og/ttkwidgets/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2S13Og/ttkwidgets/setup.py", line 9
        def read(file_name: str):
                          ^
    SyntaxError: invalid syntax
    ----------------------------------------

**Comment by RedFantom** [comment]
Well, that's embarrassing. Sorry about that!

I'm fixing it right now. I already yanked the release on PyPI and will make a 0.12.1 which has this specification included. I did remove the classifier, but forgot about this kwarg.

**Comment by namruf15** [comment]
Thanks for quick reaction! How does the procedure for releasing new version to PyPi looks like? Still I can see that newest version hasn't been released and version 0.11.0 is at the top.

**Comment by RedFantom** [comment]
I've been away for a few days, but in the meantime I have uploaded 0.12.1 to PyPI and it should be installable for Python 3 users.

The procedure that I currently do is as follows:
- Make a new commit 'Bump version number to vX.X.X`
- Tag that commit
- Push, then wait for CI to complete successfully
- Run the tests locally
- Create an sdist package, install it and do a sanity check of the sdist with a project that makes use of a couple of widgets from the package
- Finally, upload the package to PyPI with twine


As Python 2 is EOL, I won't be providing new releases for Python 2 users. I hope this answers all your questions, but don't hesitate to post again if it doesn't!
