### ISSUE TITLE
Change license to GNU LGPL instead of GPL?

### ISSUE THREAD

**Issue by larryw3i** [TkinterEP/ttkwidgets#95]
I think changing the license for this repository to LGPL would make this repository be used by more people and make tkinter more popular.😂 @RedFantom 
Regards.
larryw3i

**Comment by Dogeek** [comment]
The GPL license is good imo, having to disclose the license alongside derivated work is a good thing for this project. If we were to change the license, it would be to the Tk/Tcl license in my opinion

> The authors hereby grant permission to use, copy, modify, distribute, and license this software and its documentation for any purpose, provided that existing copyright notices are retained in all copies and that this notice is included verbatim in any distributions. No written agreement, license, or royalty fee is required for any of the authorized uses. Modifications to this software may be copyrighted by their authors and need not follow the licensing terms described here, provided that the new terms are clearly indicated on the first page of each file where they apply.

https://www.tcl.tk/software/tcltk/license.html
